// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: GenerateProto.proto

package protoFiles

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputSendData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendData      []byte                 `protobuf:"bytes,1,opt,name=SendRequestGrpc,proto3" json:"SendRequestGrpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputSendData) Reset() {
	*x = InputSendData{}
	mi := &file_GenerateProto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputSendData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputSendData) ProtoMessage() {}

func (x *InputSendData) ProtoReflect() protoreflect.Message {
	mi := &file_GenerateProto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputSendData.ProtoReflect.Descriptor instead.
func (*InputSendData) Descriptor() ([]byte, []int) {
	return file_GenerateProto_proto_rawDescGZIP(), []int{0}
}

func (x *InputSendData) GetSendData() []byte {
	if x != nil {
		return x.SendData
	}
	return nil
}

type OutputSendData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesOutput   []byte                 `protobuf:"bytes,1,opt,name=BytesOutput,proto3" json:"BytesOutput,omitempty"`
	Error         []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputSendData) Reset() {
	*x = OutputSendData{}
	mi := &file_GenerateProto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputSendData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputSendData) ProtoMessage() {}

func (x *OutputSendData) ProtoReflect() protoreflect.Message {
	mi := &file_GenerateProto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputSendData.ProtoReflect.Descriptor instead.
func (*OutputSendData) Descriptor() ([]byte, []int) {
	return file_GenerateProto_proto_rawDescGZIP(), []int{1}
}

func (x *OutputSendData) GetBytesOutput() []byte {
	if x != nil {
		return x.BytesOutput
	}
	return nil
}

func (x *OutputSendData) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_GenerateProto_proto protoreflect.FileDescriptor

const file_GenerateProto_proto_rawDesc = "" +
	"\n" +
	"\x13GenerateProto.proto\x12\x05test1\"+\n" +
	"\rInputSendData\x12\x1a\n" +
	"\bSendRequestGrpc\x18\x01 \x01(\fR\bSendRequestGrpc\"H\n" +
	"\x0eOutputSendData\x12 \n" +
	"\vBytesOutput\x18\x01 \x01(\fR\vBytesOutput\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error2N\n" +
	"\x0eSendingGetting\x12<\n" +
	"\rGettingNewKey\x12\x14.test1.InputSendData\x1a\x15.test1.OutputSendDataB\x1bZ\x19github.com/f0ggee/Filesbeb\x06proto3"

var (
	file_GenerateProto_proto_rawDescOnce sync.Once
	file_GenerateProto_proto_rawDescData []byte
)

func file_GenerateProto_proto_rawDescGZIP() []byte {
	file_GenerateProto_proto_rawDescOnce.Do(func() {
		file_GenerateProto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GenerateProto_proto_rawDesc), len(file_GenerateProto_proto_rawDesc)))
	})
	return file_GenerateProto_proto_rawDescData
}

var file_GenerateProto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GenerateProto_proto_goTypes = []any{
	(*InputSendData)(nil),  // 0: test1.InputSendData
	(*OutputSendData)(nil), // 1: test1.OutputSendData
}
var file_GenerateProto_proto_depIdxs = []int32{
	0, // 0: test1.SendingGetting.GettingNewKey:input_type -> test1.InputSendData
	1, // 1: test1.SendingGetting.GettingNewKey:output_type -> test1.OutputSendData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GenerateProto_proto_init() }
func file_GenerateProto_proto_init() {
	if File_GenerateProto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GenerateProto_proto_rawDesc), len(file_GenerateProto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_GenerateProto_proto_goTypes,
		DependencyIndexes: file_GenerateProto_proto_depIdxs,
		MessageInfos:      file_GenerateProto_proto_msgTypes,
	}.Build()
	File_GenerateProto_proto = out.File
	file_GenerateProto_proto_goTypes = nil
	file_GenerateProto_proto_depIdxs = nil
}
