// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: GenerateProto.proto

package protoFiles

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SendingGetting_GettingNewKey_FullMethodName = "/test1.SendingGetting/GettingNewKey"
)

// SendingGettingClient is the client API for SendingGetting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendingGettingClient interface {
	GettingNewKey(ctx context.Context, in *InputSendData, opts ...grpc.CallOption) (*OutputSendData, error)
}

type sendingGettingClient struct {
	cc grpc.ClientConnInterface
}

func NewSendingGettingClient(cc grpc.ClientConnInterface) SendingGettingClient {
	return &sendingGettingClient{cc}
}

func (c *sendingGettingClient) GettingNewKey(ctx context.Context, in *InputSendData, opts ...grpc.CallOption) (*OutputSendData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutputSendData)
	err := c.cc.Invoke(ctx, SendingGetting_GettingNewKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendingGettingServer is the server API for SendingGetting service.
// All implementations must embed UnimplementedSendingGettingServer
// for forward compatibility.
type SendingGettingServer interface {
	GettingNewKey(context.Context, *InputSendData) (*OutputSendData, error)
	mustEmbedUnimplementedSendingGettingServer()
}

// UnimplementedSendingGettingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSendingGettingServer struct{}

func (UnimplementedSendingGettingServer) GettingNewKey(context.Context, *InputSendData) (*OutputSendData, error) {
	return nil, status.Error(codes.Unimplemented, "method GettingNewKey not implemented")
}
func (UnimplementedSendingGettingServer) mustEmbedUnimplementedSendingGettingServer() {}
func (UnimplementedSendingGettingServer) testEmbeddedByValue()                        {}

// UnsafeSendingGettingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendingGettingServer will
// result in compilation errors.
type UnsafeSendingGettingServer interface {
	mustEmbedUnimplementedSendingGettingServer()
}

func RegisterSendingGettingServer(s grpc.ServiceRegistrar, srv SendingGettingServer) {
	// If the following call panics, it indicates UnimplementedSendingGettingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SendingGetting_ServiceDesc, srv)
}

func _SendingGetting_GettingNewKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputSendData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendingGettingServer).GettingNewKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SendingGetting_GettingNewKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendingGettingServer).GettingNewKey(ctx, req.(*InputSendData))
	}
	return interceptor(ctx, in, info, handler)
}

// SendingGetting_ServiceDesc is the grpc.ServiceDesc for SendingGetting service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendingGetting_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test1.SendingGetting",
	HandlerType: (*SendingGettingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GettingNewKey",
			Handler:    _SendingGetting_GettingNewKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "GenerateProto.proto",
}
